name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103' # SDK Version to use.
    - name: Build with dotnet
    - run: dotnet build MetasysServices --configuration Release
    - name: Unit Tests
      run: dotnet test
